package app.dokt.gradle

import app.dokt.generator.application.Application
import app.dokt.generator.code.KotlinSources
import app.dokt.generator.domain.model.BoundedContextModelReader

class GradleApplication(private val project: DomainProject) : Application {
    override val appDescription get() = project.description

    override val appDisplayName get() = project.description

    override val appName: String get() = project.name

    override val boundedContexts by lazy {
        BoundedContextModelReader.readContexts(KotlinSources(project.commonMainKotlin.toPath()))
    }

    override val domainSources by lazy { project.commonMainKotlin.toString() }

    override val generated by lazy { project.generatedDir.toString() }

    override val generatedSources by lazy { project.generatedCommonMainDir.toString() }

    override val generatedTestSources by lazy { project.generatedCommonTestDir.toString() }

    override val group get() = project.group.toString()
}
