package app.dokt.gradle

import app.dokt.generator.application.Application
import app.dokt.generator.building.MultiProject
import app.dokt.generator.domain.model.BoundedContextModelReader
import org.gradle.api.Project

class GradleApplication(private val project: Project, private val multiProject: MultiProject) : Application {
    override val appDescription get() = project.description

    override val appDisplayName get() = project.description

    override val appName: String get() = project.name

    override val boundedContexts by lazy {
        BoundedContextModelReader.readContexts(multiProject.src.common.main.kotlin)
    }

    override val domainSources by lazy { multiProject.src.common.main.kotlin.path.toString() }

    override val generated by lazy { project.buildDirectory.toString() }

    override val generatedSources by lazy { project.commonMainDir.toString() }

    override val generatedTestSources by lazy { project.commonTestDir.toString() }

    override val group get() = project.group.toString()
}
